### PR TITLE
Fix/redundant rpc calls

### LINKED ISSUE #12: Redundant block fetches most likely 2x-ing RPC calls
## Describe the bug 
The branches introduced to enhance some features like event monitoring on the cacher has very likely 2xd the number of RPC calls by increasing redundancy.

To be reviewed further.

## To Reproduce
**Affected versions**:

1. 
2. 
3.

**Expected behavior**

_to be filled_

**Proposed Solution**

_to be filled_

**Caveats**

_to be filled_

**Additional context**

_to be filled_

### PR DESCRIPTION
**Pull request by Seth-Schmidt**
Fixes https://github.com/PowerLoom/protocol-state-cacher/issues/12 https://github.com/PowerLoom/protocol-state-cacher/issues/14

### Checklist
- [x] My branch is up-to-date with upstream/main branch.
- [x] Everything works and tested for major version of Python/NodeJS/Go and above.
- [x] I ran pre-commit checks against my changes.
- [x] I've written tests against my changes and all the current present tests are passing.

### Current behaviour
The system previously made redundant RPC calls to fetch block information, particularly when the required block was the latest block and had already been fetched. Additionally, the batch size for flushing slot information to Redis was hardcoded, and logging in some areas used generic functions like `log.Println` and `log.Printf` which didn't provide specific log levels.

### New expected behaviour
The system now optimizes block fetching by reusing the already fetched latest block if it's the target block for processing, thereby reducing unnecessary RPC calls. The batch size for flushing slot information to Redis is now configurable via the `REDIS_FLUSH_BATCH_SIZE` environment variable, defaulting to 100 if not set. Logging has been improved by utilizing more specific log levels (e.g., `log.Info`, `log.Errorf`, `log.Warnf`) for better clarity and diagnostics.

#### Added
- Configuration for `REDIS_FLUSH_BATCH_SIZE` via an environment variable. This allows for flexible adjustment of how many slot updates are batched before being written to Redis.
- Corresponding setting `RedisFlushBatchSize` in `config/settings.go` to load and use this new configuration.

#### Changed
- Optimized the `MonitorEvents` function in `pkgs/prost/processor.go` to avoid redundant RPC calls. It now checks if the block to be processed is the `latestBlock` (which might have been fetched if `BlockOffset` is 0) and reuses it instead of re-fetching.
- The `SlotManager` in `pkgs/prost/processor.go` now uses the configurable `RedisFlushBatchSize` from `config.SettingsObj` instead of a hardcoded value.
- Replaced generic logging calls (e.g., `log.Println`, `log.Printf`) with level-specific logging (`log.Info`, `log.Errorf`, `log.Warnf`, `log.Debugf`, `log.Infof`) throughout `pkgs/prost/processor.go` for improved log clarity and filtering capabilities.

#### Fixed
- Reduced unnecessary Ethereum RPC calls by intelligently reusing pre-fetched block data when processing the latest block.

## Deployment Instructions
- Ensure the new environment variable `REDIS_FLUSH_BATCH_SIZE` is set in your deployment environment if you wish to use a value different from the default of 100. For example, in your `.env` file:
  `REDIS_FLUSH_BATCH_SIZE=100`

### CODE REVIEW

**Review by anomit — APPROVED** [review]
Deployed on staging sequencer with latest changes. Working correctly.

File: pkgs/prost/processor.go [hunk 1]
```diff
@@ -63,14 +63,25 @@ func (ep *EventProcessor) MonitorEvents() {
```
Comment (anomit) [inline pkgs/prost/processor.go:63]: For the first run with `lastProcessedBlock=0` , the `for` loop will begin iterating from `targetBlockNumber+1` because `lastProcessedBlock = targetBlockNumber`, and how will the conditional of `blockNum <= targetBlockNumber` be satisfied?

@Seth-Schmidt

**Review by anomit — APPROVED** [review]
LGTM
